// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('D:/github/iles-repro/src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('D:/github/iles-repro/src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('D:/github/iles-repro/src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('D:/github/iles-repro/src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('D:/github/iles-repro/src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('D:/github/iles-repro/src/components/icons/IconTooling.vue')['default']
    Island: typeof import('iles')['Island']
  }
}

export { }
